### ISSUE TITLE
Sync painfully slow

### ISSUE THREAD

**Issue by rex4539** [zingolabs/zingo-pc#102]
Zingo PC 1.0.0

**Describe the bug**
Blockchain sync is painfully slow and it will likely never finish because new block creation is probably faster than the sync process. Current sync speed is approximately 00.01% per hour for the last 3 days.

**To Reproduce**
1. Restore wallet from block 735000.
2. Wait for sync process to reach spam transactions.

**Expected behavior**
Wallet syncs fast.

**Desktop (please complete the following information):**
 - OS: macOS 14.0
 - Browser Safari
 - Version 17.0

**Additional context**
MacBook Pro 6-Core Intel Core i7 2,6 GHz

**Comment by juanky201271** [comment]
Thanks for the report, I hope you have a better experience with the new version (if you can install it, :D). 
Please tell us about how is the sync process in the release v1.0.1.
Thanks in advance, and thanks for testing it...
