### ISSUE TITLE
Zingo PC 1.0.1 shows green window after launch on Intel macOS and nothing else

### ISSUE THREAD

**Issue by rex4539** [zingolabs/zingo-pc#103]
<img width="1462" alt="Screenshot 2023-08-25 at 23 01 36" src="https://github.com/zingolabs/zingo-pc/assets/227442/221af604-925e-492a-bcfd-6ec2364a1214">

**Comment by juanky201271** [comment]
I'm guessing you are using this file` Zingo.PC-1.0.1.dmg `, right? Because there are two different DMG's in the release github repo.

**Comment by rex4539** [comment]
Correct

**Comment by juanky201271** [comment]
Thanks I reproduce the problem now, working on it. Sorry for the inconvenience...

**Comment by juanky201271** [comment]
I just uploaded a new binary for Intel Mac X64, I tried myself and it works, I hope you don't have any problems installing it. Thanks & sorry for the issue.

**Comment by rex4539** [comment]
Same issue with 1.0.2

**Comment by juanky201271** [comment]
Thanks, I did the same process, I don't understand what happened, I'll look into it.. and so sorry for the inconvenience.

**Comment by juanky201271** [comment]
> Same issue with 1.0.2

I just upload a new binary, and I could install in my Intel Mac, I hope works for you, and Thanks again.
