### ISSUE TITLE
failed to compute orchard witness: Tree does not contain a root at address Address {level: Level(0), index: 110}

### ISSUE THREAD

**Issue by juanky201271** [zingolabs/zingo-pc#109]
Ref: 
https://github.com/zingolabs/zingo-pc/assets/43755989/56f9a9c9-7947-47b3-b00c-c35896c7e050

![image](https://github.com/zingolabs/zingo-pc/assets/43755989/1f103ecf-3070-4af2-8698-2525d66ae437)

**Comment by juanky201271** [comment]
@AloeareV @zancas Can you take a look at this, please... maybe it's related with this one: #98

**Comment by dismad** [comment]
Please note I am using [this](https://github.com/adityapk00/lightwalletd) lightwalletd server in case it matters. Latest zebrad. Latest Xubuntu.

**Comment by juanky201271** [comment]
thanks @dismad. I forgot to mention that. 

![Screenshot_2023-09-12_11-01-54](https://github.com/zingolabs/zingo-pc/assets/43755989/14e1caba-c74f-49a5-93b3-d0a3b2652897)

**Comment by juanky201271** [comment]
The same thing here: https://github.com/zingolabs/zingolib/issues/455#issue-1870531981

**Comment by dismad** [comment]
Im not sure its sending tx's properly with lightwalletd. Can you send *any* tx's successfully?

`{"app":"lightwalletd","end":2224913,"level":"info","method":"GetBlockRange","msg":"Service","peer_addr":"127.0.0.1","start":2224913,"time":"2023-09-12T16:00:30-07:00"}
{"app":"lightwalletd","level":"info","msg":"Refreshing mempool","time":"2023-09-12T16:00:30-07:00"}
`

**Comment by juanky201271** [comment]
this one, for instance: `c86088eab7c11216ebd88b7f47ed3d78a8f2cda925716a78318822dfd01d6320`

**Comment by juanky201271** [comment]
@dismad can you confirm that this Bug disappeared using the last commit of zingo-pc/dev???? thanks in advance.

**Comment by juanky201271** [comment]
@dismad I'm closing this issue... if you have the same problem again feel free to reopen it and thanks for reporting...
