### ISSUE TITLE
Wallet File version "22"  is from future version of zingo

### ISSUE THREAD

**Issue by pacu** [zingolabs/zingo-pc#125]
Please make sure you have the latest Zingo PC. 

**Describe the bug**
When launching Zingo PC 1.0.3 for Mac OS (ARM64)
Error Initializing Lightclient
Error: Wallet file version "22" is from future version of zingo
<img width="954" alt="image" src="https://github.com/zingolabs/zingo-pc/assets/484008/3a866430-94b3-48c1-af43-d155b1eff155">

**To Reproduce**
1. download Zingo PC 1.0.3
2. install it
3. launch it

**Expected behavior**
it launches

**Desktop (please complete the following information):**
 - OS: Mac OS Ventura 13.5.2 (22G91)

**Additional Context**

I have a Zecwallet lite wallet from long ago. if they share the same data-dir, this might be the cause of the issue

**Comment by juanky201271** [comment]
I'm sure that @AloeareV have a better explanation... but I believe that your `zingo-wallet.dat` is a little bit old... and the new features in zingolib cannot read that file structure...
Fast solution: `delete current wallet file`, and after that create or restore...

I think the actual version is: **28**

2023-10-16T19:34:06.660500Z  INFO zingo_cli: data_dir: wallets
2023-10-16T19:34:06.788325Z  INFO zingolib::wallet: Reading wallet version **28**
2023-10-16T19:34:06.795061Z  INFO zingolib::wallet: Keys in this wallet:
2023-10-16T19:34:06.795152Z  INFO zingolib::wallet:   - Orchard Spending Key
2023-10-16T19:34:06.795234Z  INFO zingolib::wallet:   - Sapling Extended Spending Key
2023-10-16T19:34:06.795297Z  INFO zingolib::wallet:   - transparent extended private key
2023-10-16T19:34:06.812724Z  INFO zingo_cli:
2023-10-16T19:34:06.812816Z  INFO zingo_cli: Starting Zingo-CLI
2023-10-16T19:34:06.812884Z  INFO zingo_cli: Light Client config ZingoConfig { lightwalletd_uri: RwLock { data: https://mainnet.lightwalletd.com:9067/, poisoned: false, .. }, chain: Mainnet, reorg_buffer_offset: 0, monitor_mempool: true, wallet_dir: Some("wallets"), wallet_name: "zingo-wallet.dat", logfile_name: "zingo-wallet.debug.log" }

PS: If you really need to access that old wallet file, I can give you a old `commit` in the repo, and maybe you can open the wallet properly.

**Comment by pacu** [comment]
It's the first time ever I install Zingo PC, then it's probably that I have ZecWallet-lite installed as well. 

Then we probably need a feature to fix this, which is Zingo PC using a different directory or provide a customization point for this since anyone being a ZecWallet user will face this issue if they install Zingo PC.

**Comment by juanky201271** [comment]
The two apps share the folder, but not the same file... I'm sure you in same point used zingo-pc from source... because if you can find the `zingo-wallet.dat` file in your computer.....
Another clue is: the error message tells the version of your wallet file: `22`... mmmmm, this is really weird if you didn't use at all zingo-pc...

**Comment by pacu** [comment]
Uhmm, what about Zingo-CLI?

**Comment by juanky201271** [comment]
I don't think so, because zingo-cli stores the file in the repo itself in `/wallets`... and zingo-pc stores the file in MAC in: `<<User>>/Library/Application Support/Zcash`

**Comment by juanky201271** [comment]
@pacu Is there something more I can help you with?

**Comment by pacu** [comment]
I'm going to spend some time today to check this out and see what's originating the problem based on the information you gave me and get back to you. Thanks! I'll write my conclusions here

**Comment by juanky201271** [comment]
Perfect, thanks.

**Comment by pacu** [comment]
@juanky201271 I checked my `~/Library/Application Support/Zcash` directory and I have a `zingo-wallet.dat` file there.

If I rename it, Zingo PC starts correctly.
<img width="1294" alt="image" src="https://github.com/zingolabs/zingo-pc/assets/484008/21a83067-54a5-4685-a232-4c47f12404ab">


Is this expected behavior?

**Comment by juanky201271** [comment]
Yes, It is. @pacu

**Comment by pacu** [comment]
This is the default MacOS default `data-dir` of zingo-cli isn't it?

If so, maybe it's a good idea to figure a way for Zingo PC to have its own wallet location to avoid any conflicts.

**Comment by juanky201271** [comment]
@AloeareV @zancas @Oscar-Pepper @fluidvanadium 

These are the default paths for the zingo-pc wallet file:
- Linux: `~/.zcash/zingo-wallet.dat`
- MAC: `~/Library/Application Support/Zcash`
- Windows: `c:/Users/<user>/AppData/Roaming/Zcash`

This folder is the same that is using ZecWallet for its wallet file, and it can be really confusing to see both files in the same place, IMO. This process have nothing to do with zingo-pc, the saving process occurs in zingolib, and the Path is defined in zingolib as well.

Maybe we can create our own folder in the same place, something like:
- Linux: `~/.zingolabs/zingo-wallet.dat`
- MAC: `~/Library/Application Support/ZingoLabs`
- Windows: `c:/Users/<user>/AppData/Roaming/ZingoLabs`

@pacu What do think about this solution? or you are thinking in another way...

**Comment by pacu** [comment]
I think that users will expect an application using it's own "bundle". 

But this is not trivial, since we have released versions out. It might be a challenge keeping a backwards compatibility with existing users.

**Comment by juanky201271** [comment]
IMO the fact that the wallet file is in different place that the path where zingo-pc is installed, for me is something good, you can perfectly uninstall the App and install it again and you don't remove your wallet file... but sharing the same folder with zecwallet... I don't think this is optimal. 
But I totally agree with it will be a big challenge to keep a backwards compatibility.

**Comment by juanky201271** [comment]
Our users perfectly know where the files are, and it is easy to identify `zingo-wallet.dat` in the `Zcash` folder. For now, I don't think it's a good idea to change this. Thanks for noticed it.
