### ISSUE TITLE
Wallet hangs when changing net

### ISSUE THREAD

**Issue by autotunafish** [zingolabs/zingo-pc#209]
Please make sure you have the latest Zingo PC. 

**Describe the bug**

When changing the net from Main to Test or Regtest, the wallet hangs with the errors pictured, starting with "address book Error: ENOENT: no such file or directory, open '/home/john/.config/Zingo PC/AddressBook.json'".

-
Normal start on Mainnet

![Screenshot from 2024-10-10 10-59-45](https://github.com/user-attachments/assets/bb4665c9-d039-4161-9f9c-12cf60cfb0db)

-
Switching to a valid testnet node, though seemingly this is not actionable to changing the outcome.

![Screenshot from 2024-10-10 11-06-56](https://github.com/user-attachments/assets/2ac09f76-2bff-4ba9-ac76-0d5efa3e6368)

-
After applied changes, the wallet hangs.

![Screenshot from 2024-10-10 11-07-33](https://github.com/user-attachments/assets/4ae04ce5-3874-4f80-a7cb-3155be595310)

**To Reproduce**
1. Go to Server settings
2. Change to Testnet or Regtest
3. Switch server and apply
4. See error. The problem can be reproduced 100% of the time.

**Expected behavior**
The wallet should work properly of course, but it should certainly not hang forever and not allow access to any settings.

**Desktop (please complete the following information):**
 - OS: Ubuntu 22.04.5 LTS x86_64, Kernel: 6.5.0-35-generic, bash 5.1.16 

 - Browser: Brave 1.70.126 https://brave.com/latest/
 - Version: Zingo-PC 1.4.3

**Additional context**

**Comment by juanky201271** [comment]
Thanks for reporting... @autotunafish 
I'll look into it really soon... I mean now.

**Comment by juanky201271** [comment]
@autotunafish Can you pull the new commits and try again?
I saw the problem & hopefully I solved it.
Please let me know if you have others problems.

**Comment by autotunafish** [comment]
ok I'll letya know

**Comment by autotunafish** [comment]
That seemed to do the the trick! I'll post anything else I run into, thank you so much! : ) (i'll let you close this)

**Comment by juanky201271** [comment]
Thank you for check it out. Closing...
