### ISSUE TITLE
Can't send from transparent address

### ISSUE THREAD

**Issue by gagarin55** [zingolabs/zingo-pc#211]
**Describe the bug**
I have ZEC on transparent address but on Send screen it says that Spendable amount is zero

**Expected behavior**
I want to be able to send ZEC from transparent address

**Desktop (please complete the following information):**
 - OS: Linux

**Comment by juanky201271** [comment]
Thanks for reporting @gagarin55 
Yes, you are right the transparent amount in Zingo is not spendable, you always can shield the transparent funds to orchard, and after that you can spend it.
