### ISSUE TITLE
two same addresses in the addressbook - address duplicate

### ISSUE THREAD

**Issue by juanky201271** [zingolabs/zingo-pc#23]
The App check about the same `label` but no about the same address... I don't know if make any sense to have the same address under different labels.

@zancas What do you think? this make sense?

**Comment by zancas** [comment]
It's plausible that this caused by the same bug as the memo-duplication that @AloeareV is working on.   Can we add a test that surfaces this bug?   @fluidvanadium ?

**Comment by juanky201271** [comment]
Oh, this is more simple then that... sorry for my bad explanation... I'm going to try again:
In zingo-pc you can create the address book by yourself (it is a JSON file in the PC) and you have to fill two values to add a row, label & address. You manually can create the number of rows that you want, filling the label and copy/paste whatever address you want. It's for now, a really rustic feature.

And I noticed these:
* you cannot create two records with the same label (I feel this is correct)
* you CAN create two records with the same address (here is my question... I don't know if this make sense or not).

Maybe all of this doesn't matter because in a short term we have to change this behavior aligned with the new zingolib-memo implementation... @zancas

**Comment by zancas** [comment]
Ahh...  I see interesting.   I am not ready to have an opinion on this.  I need to think about it.

**Comment by juanky201271** [comment]
Closing this in favor of: #186
