### ISSUE TITLE
The address is not a valid Zcash address

### ISSUE THREAD

**Issue by Edicksonjga** [zingolabs/zingo-pc#52]
**Describe the bug**
When using the URI Payments option, an error appears indicating that the transaction is not recognized.

**To Reproduce**
1. Enter Payments URI
2. Paste the payment URI
3. Confirm
4. Error, the address is not a Zcash address

![IMG_20230509_205516_818.png](https://github.com/zingolabs/zingo-pc/assets/37910384/26414799-7470-4efc-91d4-6cf81476b860)

![IMG_20230509_205519_308.png](https://github.com/zingolabs/zingo-pc/assets/37910384/d312a28b-8103-4e4d-ac34-399058c3b043)

The option identifies z-addresses and Zcash Unified Addresses as invalid addresses when pasting a payment URI.

**Expected behavior**
By pasting the payment URI and Confirm you should accept the address if it is a Zcash address.

**Desktop:**
 - OS: Windows 10
 - Version: v.0.0.1

**Additional context**
The error occurs with or without a memo in the payment URI.

**Comment by juanky201271** [comment]
Can you post here the URI that you are trying to use? thanks.

**Comment by Edicksonjga** [comment]
> Can you post here the URI that you trying to use? thanks.

1. Free2Z:
zcash:u19cd4nhq2l0gpn985h8d63xkqj2man6gpzm8fkjczzy7lkgaermgv5ueuyp86r4eemwef0x4mavg9mmuycxcar3x477mrp98p97x7l3qvzrut6ap4y9c8xuy7hcq8q90ek6rhkd3xlufshjyv7dzpv4mx428pzq568jrye77hratw4tjwdwqekqljgyalnm8l3y72sqdd9jed6k65vpf?amount=0.500&memo=

2. ZECpage:
zcash:zs1j29m7zdhhyy2eqrz89l4zhk0angqjh368gqkj2vgdyqmeuultteny36n3qsm47zn8du5sw3ts7f?amount=0.001
