### ISSUE TITLE
New button to shield all funds.

### ISSUE THREAD

**Issue by juanky201271** [zingolabs/zingo-pc#57]
We need to include a new button to do that.

**Comment by elijahhampton** [comment]
Hi. @juanky201271  I created a PR in regard to this issue:

https://github.com/zingolabs/zingo-pc/pull/67

**Comment by juanky201271** [comment]
@elijahhampton 

First of all, I'm going to explain to you the idea of this `shield` functionality... @zancas Please, if I say something wrong or not accurate, please feel free to correct me.

We want the possibility of `shield` each `pool` (sapling or transparent) separately... not `'all'`.

I mean, two buttons are needed, one for sapling and one for transparent. you can use instead `all` -> `sapling` or `transparent` (you can take a look to `zingolib` command `shield` for being sure).

**Comment by elijahhampton** [comment]
No problem. I will refactor and correct.

**Comment by Edicksonjga** [comment]
@juanky201271 , @elijahhampton , in addition to the buttons to "Shield Funds" from the "Receive" tab, do you plan to add a button on the Dashboard or header?

**Comment by juanky201271** [comment]
@elijahhampton How's it going...? Let me know if you have any questions or something... Thanks.

**Comment by elijahhampton** [comment]
> @elijahhampton How's it going...? Let me know if you have any questions or something... Thanks.

@juanky201271 Sure. A few questions. Do you have a discord or chat channel I can jump into?

**Comment by juanky201271** [comment]
> > @elijahhampton How's it going...? Let me know if you have any questions or something... Thanks.
> 
> @juanky201271 Sure. A few questions. Do you have a discord or chat channel I can jump into?

@zancas Can you help @elijahhampton to access to the appropriate chat for discussing about `zingo-pc`? Thanks in advance.

**Comment by zancas** [comment]
Hi @elijahhampton join this discourse forum:

https://forum.zcashcommunity.com/

You can PM me there.  I am "zancas".

**Comment by elijahhampton** [comment]
> @elijahhampton
> 
> First of all, I'm going to explain to you the idea of this `shield` functionality... @zancas Please, if I say something wrong or not accurate, please feel free to correct me.
> 
> We want the possibility of `shield` each `pool` (sapling or transparent) separately... not `'all'`.
> 
> I mean, two buttons are needed, one for sapling and one for transparent. you can use instead `all` -> `sapling` or `transparent` (you can take a look to `zingolib` command `shield` for being sure).

@juanky201271 

Sorry this comment confused me a little because as I understand sapling funds are already shielded.

So you are requesting the following modification:

1. Shield transparent -> sapling
2. Shield sapling -> unified (Basically sending sapling funds to the users unified address)

Also, I apologize for the delay. I was having a hard time accessing testnet ZEC to test the feature. Today I want to buy some ZEC so I figured why not test the MR while doing that. I will finish it this weekend.

**Comment by juanky201271** [comment]
I'm sorry... you are right, sapling funds are already shielded.

But the idea is the same:
- promote sapling funds to orchard.
- shield transparent funds to orchard.

The user can want to choose those funds separately.

**Comment by juanky201271** [comment]
> @juanky201271 , @elijahhampton , in addition to the buttons to "Shield Funds" from the "Receive" tab, do you plan to add a button on the Dashboard or header?

I was thinking about this, and honestly I don't see this clearly... Can you elaborate more your proposal of putting another button in the dashboard???? 
Maybe is a good thing to do this in another PR, can you open another issue with your idea about the shield button in the Dashboard? 

Thanks in advance.
