### ISSUE TITLE
Greater privacy in transactions

### ISSUE THREAD

**Issue by Edicksonjga** [zingolabs/zingo-pc#61]
Zingo (including Zingo-PC) does not manage the funds that are in the Sapling shield pool towards Sapling (when the unified address is complete), it sends the funds towards Orchard.

This causes the transaction to not be totally private, when a transaction is of type z2u or u2z they reveal the net change of funds that resulted from the transaction.

**Hypothetical case 1:**

1. User A has funds in Sapling and Orchard.
2. User B provides you with a complete unified address.
3. User A proceeds to send ZEC.
4. The wallet sends everything to Orchard and does not take advantage of the recipients of the full unified address, the net change in funds that resulted from the transaction is revealed.

![Screenshot_20230519-232204.jpg](https://github.com/zingolabs/zingo-pc/assets/37910384/6ecb1cd1-83ea-4145-bcd8-3a146bfadba0)
[Blockchain transaction](https://3xpl.com/zcash/transaction/798227db23e1115357feadaa286561a49c7c6cbd34590d647d4f0dd094d617e4).

**Expected behavior:**

The wallet should take advantage of using unified addresses and send funds from Sapling > Sapling and Orchard > Orchard in the transaction. In this way, no information is revealed and the transaction is completely private.

**Hypothetical case 2:**

1. User A has funds in Sapling.
2. User B provides a complete unified address.
3. User A proceeds to send ZEC.
4. The wallet sends the ZECs to Orchard, the net change in funds that resulted from the transaction is revealed.

![IMG_20230519_232513_322.jpg](https://github.com/zingolabs/zingo-pc/assets/37910384/9c4828e6-1404-40e8-88c4-9bd7d5f2c785)

![Screenshot_20230519-232553.jpg](https://github.com/zingolabs/zingo-pc/assets/37910384/0ec53443-f2bc-48a3-a3dd-dbe94539febd)
[Blockchain transaction](https://3xpl.com/zcash/transaction/c15fb07a737033bc542b83068aed669cf6f1695021d4f39ff77bb465f1a36375).

**Expected behavior:**

The wallet should take advantage of the recipients of the unified address to make the transaction as private as possible. In this case he should have sent to Sapling.

**Suggestion 1:**
I think it would be nice to make a change where the fund manager always takes advantage of the unified address shield receivers to keep the transaction as private as possible if the sending user has the necessary funds to complete the transaction privately.

**Suggestion 2:**
Add a transaction confirmation screen where the user can see the level of privacy of their transaction, in Zingo-PC it can be seen, but not in Zingo for mobile devices.

From Zingo-PC you can see from the confirmation pop-up window if the transaction is shielded, reveals the amount or is public.

I don't know why, but Zingo also automatically migrates funds from Sapling to Orchard when a transaction is made. I guess it is due to the automatic funds migration and shielding function to the last shielded pool added in NU5.

**Comment by juanky201271** [comment]
@Edicksonjga Can you review your Issue, please. We are working in some of this features, some of them are already fixed... Thanks in advance.
