### ISSUE TITLE
Transactions with little information

### ISSUE THREAD

**Issue by Edicksonjga** [zingolabs/zingo-pc#63]
Not much information is shown in the transaction details when you make a transaction sending the funds you have in Sapling to Orchard using your own unified address ("manual" funds migration or funds shield).

Steps:
1. Make a transaction with funds in Sapling to your own unified address.
2. Wait for the transaction to appear in the History.
3. Tap on the transaction to see more details.

**Expected behavior:**
The details window should show the amount, address, Fee, TXID and other data.

**Current behavior:**
The transaction in the History does not show data, when you touch the transaction to see more details, the only thing that shows is the fee where the amount should be and the TXID.

**It happens on Zingo mobile and Zingo PC.**

![Screenshot_20230523-201027.jpg](https://github.com/zingolabs/zingo-pc/assets/37910384/791219bb-fd1f-4aec-8976-c103fa8ccaac)

![Screenshot_20230523-201019.jpg](https://github.com/zingolabs/zingo-pc/assets/37910384/d4bb1654-af23-476f-b529-d2e1823e09c3)

![IMG_20230523_155123_379.png](https://github.com/zingolabs/zingo-pc/assets/37910384/fb759c16-db3b-4ef1-a32f-6af57e8a2808)

![IMG_20230523_155301_828.png](https://github.com/zingolabs/zingo-pc/assets/37910384/bda91511-a075-45c9-b216-dfcda72120ff)

Windows 10
Zingo PC latest 'beta' version

Techno Phantom X
Android 11
Zingo 1.2.1 (122)

**Comment by elijahhampton** [comment]
@Edicksonjga Are you open to external contributions? 

There is no need to assign me if you would like to keep the issue open for solutions/suggestions, although, I would love to make an attempt to close the issue for you.

**Comment by zancas** [comment]
Hi @elijahhampton this code is open source!   If you've gotta' hack, we're definitely interested in PRs.

**Comment by juanky201271** [comment]
@Edicksonjga What about this one...?
