### ISSUE TITLE
Bugs - Payment URIs not working, Transaction Details and Shield funds

### ISSUE THREAD

**Issue by Edicksonjga** [zingolabs/zingo-pc#71]
I have done some tests on Zingo-PC and got some small errors.

1 - **Payment URIs do not work**

Copy and paste a payment URI using the Pay URI function and wait for the wallet to process the changes.

**BUG**: the wallet does not process the URI and freezes.

2 - **Transaction details**

When trying to view the details of a transaction, the window is displayed in green, without details, without options, buttons, etc.

3) **Shield transparent balance**

There is no button to Shield the balance that is in the transparent pool.

**Desktop:**
 - OS: Windows 10
 - Version: Zingo PC 1.0.0

**Comment by Edicksonjga** [comment]
The first two bugs seem to be fixed with #70. Thanks @juanky201271 👍

**Comment by juanky201271** [comment]
Thanks, @Edicksonjga.

I think the 1 & 2 bugs are already fixed.
The 3 is in the oven... #67
