### ISSUE TITLE
libva error upon startup on Linux

### ISSUE THREAD

**Issue by BostonZcash** [zingolabs/zingo-pc#96]
On a Xubuntu 23.04 x64 system, I run either the v1.0.0 AppImage or apt-installed binary, which produces a fully-black window with menu bar, but no first-run text or buttons. It throws the following error:

```
./Zingo.PC-1.0.0.AppImage 
libva error: /usr/lib/x86_64-linux-gnu/dri/i965_drv_video.so init failed

./zingo-pc 
libva error: /usr/lib/x86_64-linux-gnu/dri/i965_drv_video.so init failed
```

However, I have another Xubuntu 23.04 x64 system (with a different package base) which does not throw this error and which runs Zingo PC successfully.

**Comment by juanky201271** [comment]
Thanks for the issue... actually I just uploaded new binaries for linux. Can you, please, do the same testing with the new files... 

@BostonZcash Thanks again.

**Comment by juanky201271** [comment]
We just created a new pre-release... https://github.com/zingolabs/zingo-pc/releases/tag/zingo-pc-1.0.1

**Comment by juanky201271** [comment]
@BostonZcash Sorry to interrupt... but, do you have the chance to install the new release v1.0.1? I encourage to install it because the syncing hopefully will be faster. Please tell us about your experience. Thanks in advance and sorry about the issue installing.

**Comment by BostonZcash** [comment]
Appreciate the fix. I've found v1.0.1 to overcome this issue on the Linux installation I had been experiencing it on. 

However, in running this version on macOS on which I had had the same wallet imported and running successfully with v1.0.0, I'm now getting a blank black screen upon startup, similar to what had been experienced before on Linux.

If I run it with logging (`open -a Zingo\ PC.app --args --enable-logging --v=1`), do you know where logs would be saved to?

**Comment by juanky201271** [comment]
/// The directory where the wallet and logfiles will be created. By default, this will be in ~/.zcash on Linux and %APPDATA%\Zcash on Windows.

For macOS I believe the path is similar to Linux.

**Comment by juanky201271** [comment]
@BostonZcash the logs should be in: `<<User>>/Library/Application Support/Zingo PC`

**Comment by juanky201271** [comment]
@BostonZcash How's it going? some news about the installations? Thanks though.

**Comment by BostonZcash** [comment]
@juanky201271 Pardon the delay. I wasn't able to find logs in the above location, but I've found the latest v1.0.3 to resolve this on macOS. Thanks! Closing.
