### ISSUE TITLE
Error: SendResponse { error_code: -26, error_message: "16: bad-txns-orchard-unknown-anchor" }

### ISSUE THREAD

**Issue by juanky201271** [zingolabs/zingo-pc#98]
When I tried to shield my transparent balance: 0.0002.

![image](https://github.com/zingolabs/zingo-pc/assets/43755989/fdc0cf4f-aa43-4053-922b-e6098fcc968a)
![image](https://github.com/zingolabs/zingo-pc/assets/43755989/c325ed22-1c77-4a4f-9873-dee502c7e010)

cc: @zancas @AloeareV @Oscar-Pepper

**Comment by juanky201271** [comment]
seed:
`orphan diesel giggle rigid mutual inside provide meat heavy laugh grab spray color maple else weekend start small giraffe force sign tiny random maid`

birthday:
`1658696`

**Comment by AloeareV** [comment]
Is this after loading a wallet from an older version of the code? Do you know if the error persists on rescan?

**Comment by juanky201271** [comment]
> Is this after loading a wallet from an older version of the code? Do you know if the error persists on rescan?

Yes for both questions... and persist when you restore from seed as well...

**Comment by AloeareV** [comment]
Okay...the persistence on restore-from-seed disproves what I thought the bug was...good to know.

**Comment by AloeareV** [comment]
Loading this seed on zingo-cli gives me 
```
thread 'tokio-runtime-worker' panicked at 'Cound not mark note as spent', zingolib/src/blaze/update_notes.rs:129:30
note: run with `RUST_BACKTRACE=1` environment variable to display a backtrace
thread 'tokio-runtime-worker' panicked at 'called `Result::unwrap()` on an `Err` value: JoinError::Panic(Id(639), ...)', zingolib/src/blaze/update_notes.rs:162:19
```
So...that shouldn't be a panic, but I thought it would never be hit...so something's going wrong here that our tests didn't catch.

**Comment by juanky201271** [comment]
> Loading this seed on zingo-cli gives me
> 
> ```
> thread 'tokio-runtime-worker' panicked at 'Cound not mark note as spent', zingolib/src/blaze/update_notes.rs:129:30
> note: run with `RUST_BACKTRACE=1` environment variable to display a backtrace
> thread 'tokio-runtime-worker' panicked at 'called `Result::unwrap()` on an `Err` value: JoinError::Panic(Id(639), ...)', zingolib/src/blaze/update_notes.rs:162:19
> ```
> 
> So...that shouldn't be a panic, but I thought it would never be hit...so something's going wrong here that our tests didn't catch.

Yes I got the same here...
https://github.com/zingolabs/zingolib/issues/450#issuecomment-1693883516

**Comment by juanky201271** [comment]
Update: with the last `dev` of zingolib: `mob-release-1.2.5_126-310-ged383833`

I got this error:

![image](https://github.com/zingolabs/zingo-pc/assets/43755989/8f88dfe0-70a1-44a6-bf37-7b0e6b800770)

**Comment by juanky201271** [comment]
the `bad-txns-orchard-unknown-anchor` is definitely fixed while `sending`. But the similar error when you try to send from sapling is still there.

![image](https://github.com/zingolabs/zingo-pc/assets/43755989/2483b67f-d17e-4b2e-a172-96548b9781f4)

And if you try to shield transparent funds..... the `orchard` version of the bug is still there...

![image](https://github.com/zingolabs/zingo-pc/assets/43755989/e1b1a6b8-5bc8-450e-846e-93f9706a2a81)

zingolib version:

![image](https://github.com/zingolabs/zingo-pc/assets/43755989/0ee8edcf-f7e2-47fe-a89d-fde51c1923b4)

**Comment by zancas** [comment]
@juanky201271 @Edicksonjga is this issue still happening?

**Comment by juanky201271** [comment]
I just try to shield transparent funds and it works.... and I just try to upgrade sapling funds and it works as well... maybe @Edicksonjga can confirm this... but IMO the two errors:
- bad-txns-orchard-unknown-anchor
- bad-txns-sapling-unknown-anchor

are fixed....

**Comment by juanky201271** [comment]
I just try to send from orchard pool and it works, and I try to send from sapling pool and it works perfectly as well... good news. Both bugs disappeared.
